version: '3'
services:
  lampen-it-0:
    build: .
    environment: 
      - APP_NAME=lampen-it-0
    ports:
      - "3001:3000"

  lampen-it-1:
    build: .
    environment: 
      - APP_NAME=lampen-it-1
    ports:
      - "3002:3000"

  lampen-it-2:
    build: .
    environment: 
      - APP_NAME=lampen-it-2
    ports:
      - "3003:3000"