services:

# ----------------- CLOUDFLARED TUNNEL ----------------- 
  cloudflared: 
    image: cloudflare/cloudflared:latest
    container_name: lampenit-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run lampenit-tunnel
    env_file: 
      - .env
    volumes:
      - ./nginx/cloudflared:/etc/cloudflared
    networks: 
      - lampenit-net

  # ----------------- NGINX (reverse proxy) -----------------
  nginx:
    image: nginx:latest
    container_name: lampenit-nginx 
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front-end/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend-server-0
      - frontend-server-1
      - game-server-0
      - game-server-1
    networks:
      - lampenit-net
    env_file:
      - .env  

  # ----------------- React frontend servers -----------------
  frontend-server-0:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: lampenit-web-server-0
    env_file:
      - .env  
    networks:
      - lampenit-net

  frontend-server-1:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: lampenit-web-server-1
    env_file:
      - .env
    networks:
      - lampenit-net

  # ----------------- Game servers (API backend) -----------------
  game-server-0:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    container_name: lampenit-game-server-0
    env_file:
      - .env
    networks:
      - lampenit-net

  game-server-1:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    container_name: lampenit-game-server-1
    env_file:
      - .env
    networks:
      - lampenit-net

# ----------------------- DB -------------------------

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - lampenit-db-data:/var/lib/postgresql/data
    networks:
      - lampenit-net



# ----------------- Shared network -----------------
networks:
  lampenit-net:
    driver: bridge

# ----------------- Named volume for DB -----------------
volumes:
  lampenit-db-data:
