version: "3.9"

services:

  # ----------------- NGINX (reverse proxy) -----------------
  nginx:
    image: nginx:latest
    container_name: lampenit-nginx
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./front-end/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend-server-0
      - frontend-server-1
      - game-server-0
      - game-server-1
    networks:
      - lampenit-net
    env_file:
      - .env  

  # ----------------- React frontend servers -----------------
  frontend-server-0:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: lampenit-web-server-0
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_NAME=frontend-server-0
      - X_INTERNAL_AUTH=${X_INTERNAL_AUTH} 
      - JWT_SECRET=${JWT_SECRET}  
    networks:
      - lampenit-net

  frontend-server-1:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: lampenit-web-server-1
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_NAME=frontend-server-1
      - X_INTERNAL_AUTH=${X_INTERNAL_AUTH} 
      - JWT_SECRET=${JWT_SECRET}  
    networks:
      - lampenit-net

  # ----------------- Game servers (API backend) -----------------
  game-server-0:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    container_name: lampenit-game-server-0
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_NAME=game-server-0
      - X_INTERNAL_AUTH=${X_INTERNAL_AUTH} 
      - JWT_SECRET=${JWT_SECRET}  
    networks:
      - lampenit-net

  game-server-1:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    container_name: lampenit-game-server-1
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_NAME=game-server-1
      - X_INTERNAL_AUTH=${X_INTERNAL_AUTH} 
      - JWT_SECRET=${JWT_SECRET}  
    networks:
      - lampenit-net

# ----------------------- DB -------------------------

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lampenit
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - lampenit-db-data:/var/lib/postgresql/data
    networks:
      - lampenit-net


# ----------------- Shared network -----------------
networks:
  lampenit-net:
    driver: bridge

# ----------------- Named volume for DB -----------------
volumes:
  lampenit-db-data:
