services:

# ----------------- CLOUDFLARED TUNNEL ----------------- 
  cloudflared: 
    image: cloudflare/cloudflared:latest
    container_name: lampenit-cloudflared
    restart: unless-stopped
    env_file: 
      - .env
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks: 
      - lampenit-net

  # ----------------- NGINX (reverse proxy) -----------------
  nginx:
    image: nginx:latest
    container_name: lampenit-nginx 
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front-end/build:/usr/share/nginx/html:ro
    depends_on:
      - backend-server-0
      - backend-server-1
    networks:
      - lampenit-net
    env_file:
      - .env  

  # ----------------- Backend servers -----------------
  backend-server-0:
    build:
      context: ./backend-server
      dockerfile: Dockerfile
    container_name: lampenit-backend-server-0
    env_file:
      - .env  
    networks:
      - lampenit-net

  backend-server-1:
    build:
      context: ./backend-server
      dockerfile: Dockerfile
    container_name: lampenit-backend-server-1
    env_file:
      - .env
    networks:
      - lampenit-net

# ----------------------- DB -------------------------

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - lampenit-db-data:/var/lib/postgresql/data
    networks:
      - lampenit-net


# ----------------- Shared network -----------------
networks:
  lampenit-net:
    driver: bridge

# ----------------- Named volume for DB -----------------
volumes:
  lampenit-db-data:
