tunnel: 7f1b89dc-4368-49c0-9afa-1f97bdf035f7
credentials-file: /home/chris/.cloudflared/7f1b89dc-4368-49c0-9afa-1f97bdf035f7json
origincert: /home/chris/.cloudflared/cert.pem 

ingress:
  - hostname: fishhub.ca
    service: https://localhost:443
    originRequest:
      originServerName: fishhub.ca
      insecureSkipVerify: true
  - hostname: www.fishhub.ca
    service: https://localhost:443
    originRequest:
      originServerName: fishhub.ca
      insecureSkipVerify: true
  - service: http_status:404
